name: New hiu.state.gov
description: "Main website of the U.S. Department of State, Humanitarian Information Unit"
logo: "/assets/img/hiu_logo.png"
markdown: redcarpet
timezone: America/New_York
permalink: none
#baseurl: http://localhost:8000
#url: http://localhost:8000
#destination: /var/www
baseurl: /hiu.state.gov
url: http://state-hiu.github.io/hiu.state.gov
destination: _site

# Explicit excludes, including dotfiles to be safe
exclude: [.DS_Store, .git, .gitignore, .vagrant, Gruntfile.js, Vagrantfile, package.json, node_modules, backups, _assets/img/src-images]

# Analytics
ga:
  enabled: false
  code: "UA-XXXXXX-1"

dap:
  enabled: false
  agency: DOS
  subagency: HIU

# Twitter
twittercard_enabled: true
twitter_site: "@StateHIU"

# Open Graph
opengraph_enabled: true

# Testing
debug_bootstrap: false
debug_leaflet: true

# GeoNode
# The first GeoNode is the primary one that is loaded on the homepage.
geonodes:
  - id: "state"
    name: "State GeoNode"
    layers: "http://geonode.state.gov/layers"
    wms: "http://geonode.state.gov/cors/geoserver/wms?SERVICE=WMS&REQUEST=GetCapabilities"
    tiles: "http://geonode.state.gov/geoserver/gwc/service/tms/1.0.0/geonode%3A{id}@EPSG%3A900913@png/{z}/{x}/{y}.png"

  - id: "cusco"
    name: "Cusco GeoNode"
    layers: "http://cuscogeonode.state.gov/layers"
    wms: "http://cuscogeonode.state.gov/cors/geoserver/wms?SERVICE=WMS&REQUEST=GetCapabilities"
    tiles: "http://cuscogeonode.state.gov/geoserver/gwc/service/tms/1.0.0/geonode%3A{id}@EPSG%3A900913@png/{z}/{x}/{y}.png"


# Document & Media Storage
storage_thumbnails_products: "https://s3.amazonaws.com/hiu-thumbnails/products"
storage_thumbnails_regions: "https://s3.amazonaws.com/hiu-thumbnails/regions"
storage_products: "https://s3.amazonaws.com/hiu-products"

# MapBox
mapbox_access_token: "pk.eyJ1IjoiaGl1IiwiYSI6InJWNGZJSzgifQ.xK1ndT3W8XL9lwVZrT6jvQ"
mapbox_url_tiles: "https://api.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token="
mapbox_url_utfgrid: "http://{s}.tiles.mapbox.com/v3/{id}/{z}/{x}/{y}.grid.json?callback={cb}&access_token="
