name: HIU
description: "Main website of the U.S. Department of State, Humanitarian Information Unit"
logo: "/assets/img/hiu_logo.png"
markdown: redcarpet
timezone: America/New_York
permalink: none
#baseurl: 
#url: http://localhost:8000
#destination: /var/www
baseurl: /hiu.state.gov
url: http://state-hiu.github.io/hiu.state.gov
destination: _site

# Explicit excludes, including dotfiles to be safe
exclude: [.DS_Store, .git, .gitignore, .vagrant, Gruntfile.js, Vagrantfile, package.json, node_modules, backups, _assets/img/src-images]

# Markdown Configuration
redcarpet:
  extensions: [with_toc_data]

# General
code: "https://github.com/state-hiu/hiu.state.gov"
disclaimer: "This site is produced and maintained by the U.S. Department of State, Humanitarian Information Unit.  For more information see the [About Us](/hiu.state.gov/about) page."

# Analytics
ga:
  enabled: false
  code: "UA-XXXXXX-1"

dap:
  enabled: false
  agency: DOS
  subagency: HIU

# Twitter
twittercard:
  enabled: true
  site: "@StateHIU"

# Open Graph
opengraph:
  enabled: true

# Debugging & Testing
debug:
  polyfill: false
  main: true
  angular: false
  bootstrap: false
  jquery: false
  leaflet: true

# Dependencies Management
deps:
  angular:
    version: "1.4.0-beta.4"
  jquery:
    version: "1.9.1"

# GeoNode
# The first GeoNode is the primary one that is loaded on the homepage.
geonodes:
  - id: "state"
    name: "State GeoNode"
    layers: "http://geonode.state.gov/layers"
    csw:
      xml: "http://geonode.state.gov/catalogue/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&maxRecords=1000&elementsetname=full&typenames=csw:Record&outputschema=http://www.isotc211.org/2005/gmd"
      json: "http://geonode.state.gov/catalogue/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&maxRecords=1000&elementsetname=full&typenames=csw:Record&outputschema=http://www.isotc211.org/2005/gmd&outputFormat=application/json"
    wms: "http://geonode.state.gov/cors/geoserver/wms?SERVICE=WMS&REQUEST=GetCapabilities"
    tiles: "http://geonode.state.gov/geoserver/gwc/service/tms/1.0.0/geonode%3A{id}@EPSG%3A900913@png/{z}/{x}/{y}.png"

  - id: "cusco"
    name: "Cusco GeoNode"
    layers: "http://cuscogeonode.state.gov/layers"
    csw:
      xml: "http://cuscogeonode.state.gov/catalogue/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&maxRecords=1000&elementsetname=full&typenames=csw:Record&outputschema=http://www.isotc211.org/2005/gmd"
      json: "http://cuscogeonode.state.gov/catalogue/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&maxRecords=1000&elementsetname=full&typenames=csw:Record&outputschema=http://www.isotc211.org/2005/gmd&outputFormat=application/json"
    wms: "http://cuscogeonode.state.gov/cors/geoserver/wms?SERVICE=WMS&REQUEST=GetCapabilities"
    tiles: "http://cuscogeonode.state.gov/geoserver/gwc/service/tms/1.0.0/geonode%3A{id}@EPSG%3A900913@png/{z}/{x}/{y}.png"


# Document & Media Storage
storage:
  thumbnails_products: "https://s3.amazonaws.com/hiu-thumbnails/products"
  thumbnails_regions: "https://s3.amazonaws.com/hiu-thumbnails/regions"
  thumbnails_guides: "https://s3.amazonaws.com/hiu-thumbnails/guides"
  thumbnails_platforms: "https://s3.amazonaws.com/hiu-thumbnails/platforms"
  products: "https://s3.amazonaws.com/hiu-products"

# MapBox
mapbox:
  access_token: "pk.eyJ1IjoiaGl1IiwiYSI6InJWNGZJSzgifQ.xK1ndT3W8XL9lwVZrT6jvQ"
  url_tiles: "https://api.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token="
  url_utfgrid: "http://{s}.tiles.mapbox.com/v3/{id}/{z}/{x}/{y}.grid.json?callback={cb}&access_token="
